/**
  ******************************************************************************
  * @file           : pcf8574_i2c.h
  * @brief          : PCF8574 I2C I/O expander platform interface
  ******************************************************************************
  * SPDX-License-Identifier: MIT
  * Copyright (C) 2026 Stric Roberts.
  *
  * Permission is hereby granted, free of charge, to any person obtaining a
  * copy of this software and associated documentation files (the "Software"),
  * to deal in the Software without restriction, including without limitation
  * the rights to use, copy, modify, merge, publish, distribute, sublicense,
  * and/or sell copies of the Software, and to permit persons to whom the
  * Software is furnished to do so, subject to the following conditions:
  *
  * The above copyright notice and this permission notice shall be included in
  * all copies or substantial portions of the Software.
  *
  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  * IN THE SOFTWARE.
  ******************************************************************************
  */

#ifndef PCF8574_I2C_H
#define PCF8574_I2C_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/**
 * @defgroup pcf8574_i2c PCF8574 I2C Interface
 * @brief Platform I2C interface for the PCF8574 8-bit I/O expander.
 *
 * Provide one translation unit that implements all three functions for the
 * target hardware. Each function performs one complete I2C transaction
 * (START, address, data, STOP). The implementation handles bus ownership;
 * the caller does not manage it.
 *
 * pcf8574_init() is called once at startup before any LCD operations.
 * On platforms where I2C is initialised elsewhere (such as Gecko SDK's
 * autogenerated sl_i2cspm_init.c), leave the body empty.
 *
 * See lib/src/gecko_sdk/pcf8574_i2c.c for a Gecko SDK 4.4.5 reference.
 * @{
 */

/**
 * @brief Default I2C address when address pins A0-A2 are pulled high.
 *
 * Most commercial PCF8574 LCD backpacks ship with this address. Some
 * PCF8574A-based modules use 0x3F instead. Verify against your hardware.
 */
#define PCF8574_DEFAULT_ADDR  0x27u

/**
 * @brief One-time I2C peripheral initialisation.
 *
 * Call once at startup before pcf8574_write() or pcf8574_read(). Perform
 * any I2C peripheral clock enable, GPIO configuration, or driver init here.
 * Leave the body empty if the platform initialises I2C elsewhere.
 */
void pcf8574_init(void);

/**
 * @brief Write one byte to the PCF8574 output latch.
 *
 * Each bit in @p data drives the corresponding pin: bit 0 drives P0,
 * bit 7 drives P7. Writing 1 releases the pin to its pull-up resistor;
 * writing 0 actively pulls it low.
 *
 * Performs: START, (addr << 1) | W, data, STOP.
 *
 * @param addr  7-bit I2C device address (not pre-shifted).
 * @param data  Byte to drive onto the PCF8574 output latch.
 */
void pcf8574_write(uint8_t addr, uint8_t data);

/**
 * @brief Read the current pin state from the PCF8574.
 *
 * Returns the actual logic level on each pin, not the last written value.
 * A pin written 1 that is driven low externally will read 0. Useful for
 * reading push-buttons or detecting bus contention.
 *
 * Performs: START, (addr << 1) | R, read byte, NACK, STOP.
 *
 * @param addr    7-bit I2C device address (not pre-shifted).
 * @param p_data  Output: pin-state byte received. Must not be NULL.
 * @return        0 on success, non-zero on bus error or NACK.
 */
int pcf8574_read(uint8_t addr, uint8_t *p_data);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* PCF8574_I2C_H */
