/**
  ******************************************************************************
  * @file           : pcf8574_i2c.c
  * @brief          : Gecko SDK I2CSPM implementation of the pcf8574_i2c interface
  ******************************************************************************
  * SPDX-License-Identifier: MIT
  * Copyright (C) 2026 Stric Roberts.
  *
  * Permission is hereby granted, free of charge, to any person obtaining a
  * copy of this software and associated documentation files (the "Software"),
  * to deal in the Software without restriction, including without limitation
  * the rights to use, copy, modify, merge, publish, distribute, sublicense,
  * and/or sell copies of the Software, and to permit persons to whom the
  * Software is furnished to do so, subject to the following conditions:
  *
  * The above copyright notice and this permission notice shall be included in
  * all copies or substantial portions of the Software.
  *
  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  * IN THE SOFTWARE.
  *
  * SDK dependencies:
  *   sl_i2cspm.h           Silicon Labs I2CSPM polled master driver
  *                         platform/driver/i2cspm/inc/sl_i2cspm.h
  *   em_i2c.h              EMLIB I2C peripheral driver
  *                         platform/emlib/inc/em_i2c.h
  *   sl_i2cspm_instances.h Autogenerated instance handle declarations
  *                         autogen/sl_i2cspm_instances.h
  *   Gecko SDK component: i2cspm, instance name: pcf8574 (tested: 4.4.5)
  *
  * The I2CSPM instance is initialised by sl_i2cspm_init.c before app_init().
  * pcf8574_init() is therefore a no-op on this platform.
  *
  * Instance name alias:
  *   The macro below maps the autogenerated handle name to the stable name
  *   used throughout this file. Update only this one line if the Simplicity
  *   Studio instance is renamed.
  ******************************************************************************
  */

#include <assert.h>
#include <stdbool.h>
#include <stddef.h>
#include "implement/pcf8574_i2c.h"
#include "sl_i2cspm.h"
#include "em_i2c.h"
#include "sl_i2cspm_instances.h"

/* Maps the autogenerated Simplicity Studio handle to a stable name.
 * Update if the i2cspm instance is renamed in the .slcp. */
#define pcf8574_i2c  sl_i2cspm_pcf8574

void pcf8574_init(void)
{
    /* I2C initialised by sl_i2cspm_init.c before app_init(). No action. */
}

void pcf8574_write(uint8_t addr, uint8_t data)
{
    I2C_TransferSeq_TypeDef seq;

    seq.addr        = (uint16_t)(addr << 1u);
    seq.flags       = I2C_FLAG_WRITE;
    seq.buf[0].data = &data;
    seq.buf[0].len  = 1u;

    (void)I2CSPM_Transfer(pcf8574_i2c, &seq);
}

int pcf8574_read(uint8_t addr, uint8_t *p_data)
{
    I2C_TransferSeq_TypeDef seq;
    bool b_status;
    int result;

    assert(NULL != p_data);

    b_status = (NULL != p_data);

    if (b_status)
    {
        seq.addr        = (uint16_t)(addr << 1u);
        seq.flags       = I2C_FLAG_READ;
        seq.buf[0].data = p_data;
        seq.buf[0].len  = 1u;

        b_status = (i2cTransferDone == I2CSPM_Transfer(pcf8574_i2c, &seq));
    }

    result = b_status ? 0 : -1;

    return result;
}
